- name: Windows updates
  strategy: free
  hosts: all
  gather_facts: true
  roles:
    - create-snapshot
    #- app
    #- db
    - search
    - patches
    - reboot
    #- sendmail
    #- validation-services
